# Generated by Django 4.1.7 on 2023-03-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventpass_api", "0002_venue_event_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="zip_code",
            field=models.IntegerField(),
        ),
    ]
