# Generated by Django 4.1.7 on 2023-03-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventpass_api", "0003_alter_venue_zip_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="photo_url",
            field=models.CharField(default="a string", max_length=500),
        ),
        migrations.AddField(
            model_name="event",
            name="photo_url",
            field=models.CharField(default="a string", max_length=500),
        ),
        migrations.AddField(
            model_name="venue",
            name="photo_url",
            field=models.CharField(default="a string", max_length=500),
        ),
    ]
