# Generated by Django 4.1.7 on 2023-03-31 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("eventpass_api", "0004_customer_photo_url_event_photo_url_venue_photo_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="zip_code",
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("seating", models.CharField(max_length=150)),
                ("number_of_tickets", models.IntegerField()),
                ("tickets_sold", models.IntegerField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="eventpass_api.customer",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="eventpass_api.event",
                    ),
                ),
            ],
        ),
    ]
