# Generated by Django 4.1.7 on 2023-03-31 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventpass_api", "0004_customer_photo_url_event_photo_url_venue_photo_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="zip_code",
            field=models.IntegerField(),
        ),
    ]
