# Generated by Django 4.1.7 on 2023-04-01 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("eventpass_api", "0005_alter_customer_zip_code_ticket"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="customer",
        ),
        migrations.AddField(
            model_name="customer",
            name="ticket",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to="eventpass_api.ticket",
            ),
            preserve_default=False,
        ),
    ]
