# Generated by Django 4.1.7 on 2023-04-01 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eventpass_api", "0005_alter_customer_zip_code"),
        ("eventpass_api", "0006_remove_ticket_customer_customer_ticket"),
    ]

    operations = []
