# Generated by Django 4.1.7 on 2023-04-03 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventpass_api', '0008_customer_app_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
