# Generated by Django 4.1.7 on 2023-04-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventpass_api', '0009_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(max_length=2),
        ),
    ]
