# Generated by Django 4.1.7 on 2023-04-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventpass_api", "0011_remove_customer_state_user_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.CharField(default="category", max_length=150),
        ),
    ]
